### ISSUE TITLE
Index feature_relationship_idx1b

### ISSUE THREAD

**Issue by bradfordcondon** [GMOD/Chado#46] opened 2018-01-10 18:37 UTC
[Here is the issue discussion](http://gmod.827538.n3.nabble.com/RFC-Chado-relase-v1-3-tp4048655p4048701.html)

-- The effectiveness of this will vary based on 
-- whether you have more subjects or objects. 

```
create index feature_relationship_idx1b 
  on feature_relationship (object_id, subject_id, type_id); 

create index featureloc_idx1b 
  on featureloc (feature_id, fmin, fmax); 

create index feature_idx1b 
  on feature (feature_id, dbxref_id) 
  where dbxref_id is not null; 
```

**Comment by laceysanderson** [comment] 2018-01-13 04:52
Duplicate of #47

**Closed** 2018-01-13 04:58 UTC
Labels: Chado 1.4 Suggestion
